import { CalculatorCard, CalculatorShell, CurrencyInput, money, numberValue, PageHeading } from '../../components/calculator-ui';
import { ui } from '../../lib/ui';
import { calculateTotals, useCalculator } from '../../store/calculator.store';

export function MetaCostsPage() {
  const store = useCalculator();
  const totals = calculateTotals(store);
  return <CalculatorShell><CalculatorCard><PageHeading title="Custos da Meta" description="Defina país, valor unitário e volume de templates." /><div className="p-5 md:p-6"><label className={ui.label}>País</label><select className={`${ui.input} max-w-xs`} value={store.country} onChange={(event) => store.setCountry(event.target.value)}><option>Brasil</option><option>Argentina</option><option>Estados Unidos</option><option>Portugal</option></select><div className="mt-6"><div className="hidden grid-cols-[1.2fr_1fr_.7fr_1fr] gap-3 border-b border-gray-100 pb-3 text-xs font-medium uppercase text-gray-400 dark:border-gray-800 md:grid"><span>Categoria</span><span>Valor por template</span><span>Quantidade</span><span className="text-right">Subtotal</span></div>{store.templates.map((item) => <div key={item.id} className="grid gap-3 border-b border-gray-100 py-4 dark:border-gray-800 md:grid-cols-[1.2fr_1fr_.7fr_1fr] md:items-center"><strong className="text-sm text-gray-700 dark:text-gray-300">{item.category}</strong><CurrencyInput label={`Valor ${item.category}`} value={item.value} onChange={(value) => store.updateTemplate({ ...item, value })} /><input className={`${ui.input} text-center`} type="number" min="0" value={item.quantity} placeholder="0" onChange={(event) => store.updateTemplate({ ...item, quantity: Math.floor(numberValue(event.target.value)) })} /><strong className="text-right text-sm text-gray-800 dark:text-white/90">{money.format(item.value * item.quantity)}</strong></div>)}<div className="mt-4 flex justify-between rounded-lg bg-brand-50 px-4 py-3 text-sm font-semibold text-brand-700 dark:bg-brand-500/10 dark:text-brand-400"><span>Total Meta</span><span>{money.format(totals.meta)}</span></div></div></div></CalculatorCard></CalculatorShell>;
}
